In [ ]:
# code ran on native machine to get all the desired audio clips

# import shutil
# import os
# import pandas as pd

# tsv_file = r"C:\Users\parth\Downloads\cv-corpus-13.0-delta-2023-03-09\en\validated.tsv"
# df = pd.read_csv(tsv_file, sep='\t', header=None)
# file_paths = [str(i) for i in df.iloc[1:101, 1]]
# print(file_paths)

# source_directory = r"C:\Users\parth\Downloads\cv-corpus-13.0-delta-2023-03-09\en\clips"
# destination_folder = r"C:\Users\parth\Downloads\cv-corpus-13.0-delta-2023-03-09\en\sample"

# for file_name in file_paths:
#     file_name = file_name.replace('"', '')
#     source_path = os.path.join(source_directory, file_name)
#     destination_path = os.path.join(destination_folder, file_name)
#     shutil.move(source_path, destination_path)

In [ ]:
# Loading the whisper model from HuggingFace
# In Google Colab, change runtime to use a GPU, makes this process much faster
!pip install git+https://github.com/huggingface/transformers -q
from transformers import pipeline
whisper = pipeline('automatic-speech-recognition', model = 'openai/whisper-medium', device = 0)

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 79.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 71.4 MB/s eta 0:00:00


In [ ]:
# Running the Whisper model over the first 100 clips in the validated data set
# Isolated the 100 clips with the script above, and then uploaded to google drive to work with in Colab
from google.colab import drive
import os
import warnings
import pandas as pd

# Suppress all warnings
warnings.filterwarnings("ignore")

whisper_df = pd.DataFrame(columns=['path', 'text'])

# Pull data from google drive
drive.mount("/content/drive/")
path = '/content/drive/My Drive/sample'

folder_contents  = os.listdir(path)

for clips in folder_contents:
  final_path = os.path.join(path, clips)

  # outputs text as a dictionary
  output = whisper(final_path)

  # returns only the text to put into dataframe
  text = output.get('text', '')
  whisper_df = whisper_df.append({'path': clips, 'text': text}, ignore_index=True)

whisper_df

Mounted at /content/drive/


path  \
0   common_voice_en_36536123.mp3   
1   common_voice_en_36542916.mp3   
2   common_voice_en_36552225.mp3   
3   common_voice_en_36626624.mp3   
4   common_voice_en_36630502.mp3   
..                           ...   
95  common_voice_en_37238108.mp3   
96  common_voice_en_37251984.mp3   
97  common_voice_en_37258829.mp3   
98  common_voice_en_37265606.mp3   
99  common_voice_en_37280114.mp3   

                                                 text  
0    The pine woods also made the region highly vu...  
1    Mariachi can refer to the music, the group, o...  
2    Court cases along the way have dealt with the...  
3      He translates poetry from Russian and Turkish.  
4    The white poplar, by contrast, is native to w...  
..                                                ...  
95                       My very best concert bonnet.  
96   The German population was either evacuated or...  
97   They ported the software to a new hardware an...  
98   While he was performing the rope broke which ...  
99   The king would die if any of his subjects wer...  

[100 rows x 2 columns]

In [ ]:
output_file_path = '/content/drive/My Drive/transcriptions.txt'

transcriptions = whisper_df['text']

with open(output_file_path, 'w') as file:
    # Iterate through the transcriptions and write them to the file
    for transcription in transcriptions:
        file.write(transcription + '\n')
file.close()

print(f"Transcriptions have been saved to {output_file_path}")


Transcriptions have been saved to /content/drive/My Drive/transcriptions.txt


In [ ]:
# Cleaning up the validated dataset so that it matches the whisper output
validated_df = pd.read_csv('validated.tsv', sep='\t', header=None)
clean_validated_df = pd.DataFrame(columns=['path', 'text'])
clean_validated_df['path'] = validated_df[1][1:101]
clean_validated_df['text'] = validated_df[2][1:101]

In [ ]:
clean_validated_df

path  \
1    common_voice_en_36938066.mp3   
2    common_voice_en_36827090.mp3   
3    common_voice_en_36998293.mp3   
4    common_voice_en_37238108.mp3   
5    common_voice_en_36965345.mp3   
..                            ...   
96   common_voice_en_37007728.mp3   
97   common_voice_en_36903576.mp3   
98   common_voice_en_37144043.mp3   
99   common_voice_en_36860150.mp3   
100  common_voice_en_36728917.mp3   

                                                  text  
1    One day at noon a woman fell asleep among the ...  
2    Then they scrambled round the rocks to the oth...  
3                          Dollar shops sell the rest.  
4                         My very best concert bonnet.  
5    This time, however, as the padded envelopes we...  
..                                                 ...  
96   The club was promoted to the First Division at...  
97   A woman had engaged two men to work in her vin...  
98   Slant magazine's Dana Stevens wrote in her rev...  
99                              She was born in Mecca.  
100  The game is available for play on Microsoft Wi...  

[100 rows x 2 columns]

In [ ]:
# Ensuring that the dataframes are both in the same order
whisper_df = whisper_df.sort_values(by="path")
clean_validated_df = clean_validated_df.sort_values(by="path")
whisper_df = whisper_df.reset_index(drop=True)
clean_validated_df = clean_validated_df.reset_index(drop=True)
print(whisper_df.head())
print(clean_validated_df.head())

                           path  \
0  common_voice_en_36536123.mp3   
1  common_voice_en_36542916.mp3   
2  common_voice_en_36552225.mp3   
3  common_voice_en_36626624.mp3   
4  common_voice_en_36630502.mp3   

                                                text  
0   The pine woods also made the region highly vu...  
1   Mariachi can refer to the music, the group, o...  
2   Court cases along the way have dealt with the...  
3     He translates poetry from Russian and Turkish.  
4   The white poplar, by contrast, is native to w...  
                           path  \
0  common_voice_en_36536123.mp3   
1  common_voice_en_36542916.mp3   
2  common_voice_en_36552225.mp3   
3  common_voice_en_36626624.mp3   
4  common_voice_en_36630502.mp3   

                                                text  
0  The pine woods also made the region highly vul...  
1  Mariachi can refer to the music, the group, or...  
2  Court cases along the way have dealt with the ...  
3     He translates poetry f

In [ ]:
import numpy as np

def wer(hypothesis, reference):
    # Tokenize the transcriptions into lists of words
    hypothesis_tokens = hypothesis.split()
    reference_tokens = reference.split()

    # Create a matrix to store edit distances
    d = np.zeros((len(reference_tokens) + 1, len(hypothesis_tokens) + 1))

    # Initialize the first row and column
    for i in range(len(reference_tokens) + 1):
        d[i, 0] = i
    for j in range(len(hypothesis_tokens) + 1):
        d[0, j] = j

    for i in range(1, len(reference_tokens) + 1):
        for j in range(1, len(hypothesis_tokens) + 1):

            #if the words are the same, the cost is 0, otherwise 1
            cost = 0 if reference_tokens[i - 1] == hypothesis_tokens[j - 1] else 1

            #Formula for word error rate is (insertions + deletions + substitutions)/number of words
            #This fucntion finds the shortest way to get from the reference word to the actual word
            d[i, j] = min([d[i - 1, j] + 1, d[i, j - 1] + 1, d[i - 1, j - 1] + cost])

    # Calculate WER as a percentage
    return (d[len(reference_tokens), len(hypothesis_tokens)] / len(reference_tokens)) * 100

wer_scores = []

for i in range(len(whisper_df)):
    hypothesis = whisper_df.at[i, "text"]
    reference = clean_validated_df.at[i, "text"]
    wer_score = wer(hypothesis, reference)
    wer_scores.append(wer_score)

# Calculate the overall WER as the mean (average) of all individual WERs
overall_wer = np.mean(wer_scores)

print(f"Overall WER: {overall_wer:.2f}%")



Overall WER: 15.36%


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

clip_transcriptions = whisper_df['text']
vectorizer = TfidfVectorizer()
clip_vectors = vectorizer.fit_transform(clip_transcriptions)
cosine_similarities = cosine_similarity(clip_vectors)

# A square matrix where cosine_similarities[i][j] represents the similarity between clip i and clip j
print(cosine_similarities)


[[1.         0.07411626 0.04401109 ... 0.05071203 0.07107472 0.04577948]
 [0.07411626 1.         0.04294273 ... 0.049481   0.06934939 0.04466819]
 [0.04401109 0.04294273 1.         ... 0.02148352 0.04118047 0.0382134 ]
 ...
 [0.05071203 0.049481   0.02148352 ... 1.         0.04745043 0.03436169]
 [0.07107472 0.06934939 0.04118047 ... 0.04745043 1.         0.04283512]
 [0.04577948 0.04466819 0.0382134  ... 0.03436169 0.04283512 1.        ]]


Following this, I have completed the tasks in 1.3 because it did not make sense to create a new notebook for the same data set


In [ ]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
import string
nltk.download('punkt')

# Function to tokenize and filter out punctuation
def tokenize_and_filter(text):

    words = word_tokenize(text)

    # Filter out punctuation
    words = [word for word in words if word not in string.punctuation]

    return words

# Tokenize and filter the transcriptions into words
all_words = [word for text in clip_transcriptions for word in tokenize_and_filter(text)]

# Calculate word frequency using FreqDist
word_freq = FreqDist(all_words)

# Get the 100 most common words
most_common_words = word_freq.most_common(100)

# Calculate the overall frequency of the most common words
overall_frequency = sum([freq for word, freq in most_common_words])

# Print the 100 most common words and their frequencies
print("Top 100 Most Common Words (Excluding Punctuation):")
for word, freq in most_common_words:
    print(f"{word}: {freq}")

# Print the overall frequency of the top 100 words
print(f"Overall Frequency of Top 100 Words (Excluding Punctuation): {overall_frequency}")


Top 100 Most Common Words (Excluding Punctuation):
the: 63
of: 32
and: 28
The: 27
to: 27
is: 22
a: 16
in: 15
was: 14
are: 10
He: 9
for: 9
on: 9
's: 8
with: 6
from: 6
were: 6
no: 6
his: 5
as: 5
also: 4
or: 4
have: 4
by: 4
this: 4
group: 3
they: 3
There: 3
first: 3
works: 3
that: 3
It: 3
had: 3
her: 3
between: 3
its: 3
other: 3
two: 3
not: 3
at: 3
there: 3
be: 3
made: 2
region: 2
music: 2
one: 2
impact: 2
native: 2
international: 2
South: 2
released: 2
including: 2
part: 2
all: 2
when: 2
strength: 2
A: 2
limited: 2
play: 2
most: 2
feature: 2
band: 2
This: 2
technology: 2
City: 2
ground: 2
side: 2
used: 2
current: 2
include: 2
She: 2
second: 2
new: 2
woman: 2
may: 2
female: 2
which: 2
only: 2
over: 2
it: 2
king: 2
Daniel: 2
They: 2
do: 2
time: 2
however: 2
see: 2
use: 2
different: 2
word: 2
any: 2
education: 2
pine: 1
woods: 1
highly: 1
vulnerable: 1
fires: 1
Mariachi: 1
can: 1
refer: 1
Overall Frequency of Top 100 Words (Excluding Punctuation): 502


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
import pandas as pd
from textblob import TextBlob

# Function to get sentiment scores
def get_sentiment(text):
    analysis = TextBlob(text)
    # Sentiment polarity ranges from -1 (negative) to 1 (positive)
    # Sentiment subjectivity ranges from 0 (objective) to 1 (subjective)
    return analysis.sentiment.polarity, analysis.sentiment.subjectivity

# Create new columns for sentiment polarity and subjectivity in the DataFrame
whisper_df['sentiment_polarity'], whisper_df['sentiment_subjectivity'] = zip(*clip_transcriptions.apply(get_sentiment))

whisper_df


path  \
0   common_voice_en_36536123.mp3   
1   common_voice_en_36542916.mp3   
2   common_voice_en_36552225.mp3   
3   common_voice_en_36626624.mp3   
4   common_voice_en_36630502.mp3   
..                           ...   
95  common_voice_en_37238108.mp3   
96  common_voice_en_37251984.mp3   
97  common_voice_en_37258829.mp3   
98  common_voice_en_37265606.mp3   
99  common_voice_en_37280114.mp3   

                                                 text  sentiment_polarity  \
0    The pine woods also made the region highly vu...           -0.500000   
1    Mariachi can refer to the music, the group, o...            0.000000   
2    Court cases along the way have dealt with the...            0.000000   
3      He translates poetry from Russian and Turkish.            0.000000   
4    The white poplar, by contrast, is native to w...            0.061111   
..                                                ...                 ...   
95                       My very best concert bonnet.            1.000000   
96   The German population was either evacuated or...            0.000000   
97   They ported the software to a new hardware an...            0.136364   
98   While he was performing the rope broke which ...            0.000000   
99   The king would die if any of his subjects wer...            0.000000   

    sentiment_subjectivity  
0                 0.500000  
1                 0.000000  
2                 0.000000  
3                 0.000000  
4                 0.483333  
..                     ...  
95                0.390000  
96                0.000000  
97                0.454545  
98                0.000000  
99                0.000000  

[100 rows x 4 columns]

In [ ]:
import pandas as pd
from nltk.tokenize import word_tokenize

# Function to calculate TTR for a given text
def calculate_ttr(text):
    # Tokenize the text into words
    words = word_tokenize(text)

    # Calculate the total number of tokens (words)
    total_tokens = len(words)

    # Calculate the number of unique words (types)
    unique_words = len(set(words))

    # Calculate TTR (Type-Token Ratio)
    if total_tokens > 0:
        ttr = unique_words / total_tokens
    else:
        ttr = 0.0

    return ttr



# Create a new column for group numbers (assuming 10 groups)
group_size = 10
whisper_df['group'] = (whisper_df.index // group_size) + 1

# Calculate TTR for each clip and group
whisper_df['ttr'] = clip_transcriptions.apply(calculate_ttr)

# Group by 'group' column and calculate the mean TTR for each group
grouped_ttr = whisper_df.groupby('group')['ttr'].mean().reset_index()

# Print the group-wise TTR
print(grouped_ttr)


   group       ttr
0      1  0.962163
1      2  0.977083
2      3  0.983974
3      4  0.964832
4      5  0.990909
5      6  0.962321
6      7  0.936090
7      8  0.976757
8      9  0.982188
9     10  0.973413
